### PR TITLE
add x86_64 example

### PR DESCRIPTION
**Pull request by thechampagne**

### CODE REVIEW

**Comment by xyproto** [comment]
Thank you! Seeing Assembly code warms my heart.

I'll give it a go and then merge the PR.

**Comment by thechampagne** [comment]
Will 32bit and windows versions be needed ?

**Comment by xyproto** [comment]
They are warmly welcome! Perhaps structured with directory names like `asm-x86_64-linux` and `asm-x86_64-win`?

**Comment by xyproto** [comment]
I really like the subdirectory idea. And I also think that the person submitting the PRs should have the power to select the directory names.

But, IMO, it would be an advantage if the directory names followed the existing pattern. As you know, Assembly is a language (with several different styles, such as Intel and AT&T). All the other directories are named after the programming language or the compiler. If the directory was named just 'x86_64` I would expect it to just contain machine code, perhaps in a format that could be ran with [jit](https://github.com/xyproto/jit). 🙂

**Pull request merged**
